development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdefosbaoifbaiofboisafbiosafbioasfboisaf0123456789"


test:
  secret_key_base:  "asdflkhasldfhlhsdaoifiosabfoisabfoiabaskdlflakhsdf"

production:
  secret_key_base: "523lk5h2lkjlj6nlk4n6lk4asdboisadbsaoidboaisd"