development:
  secret_token: "my_secret_token"
  secret_key_base: "523lk5h2lkjlj6nlk4n6lk4asdboisadbsaoidboaisd"


test:
  secret_key_base:  "523lk5h2lkjlj6nlk4n6lk4asdboisadbsaoidboaisd"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

